name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in my Blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "The Introvert Coder"
          feed_list: "https://blog.theintrovertcoder.in/rss.xml"
          max_post_count: 3
          commit_message: "Updated README with the latest blog posts"
          date_format: "mmm d, yyyy"
          custom_tags: "postImage/cover_image/"
          disable_html_encoding: true
          template: '<table><tr><td><a href="$url"><img width="140px" src="$postImage"></a></td><td><a href="$url">$title</a> | $date </td></tr></table>$newline'
